/**
 *
 * @author Arthur Felipe MS
 */
public class JanelaTeste extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public JanelaTeste() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        GerarRelatorio = new javax.swing.JButton();
        CancelarProcesso = new javax.swing.JButton();
        BotaoIniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SaidaInformacoes = new javax.swing.JTextPane();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuGeralProjeto = new javax.swing.JMenu();
        Informacoes = new javax.swing.JMenu();
        InfoGeral = new javax.swing.JMenuItem();
        ProjetoPasswords = new javax.swing.JMenuItem();
        SobreOAutor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Algoritmos = new javax.swing.JMenu();
        MenuCountingSort = new javax.swing.JMenuItem();
        MenuHeapSort = new javax.swing.JMenuItem();
        MenuInsertionSort = new javax.swing.JMenuItem();
        MenuMergeSort = new javax.swing.JMenuItem();
        MenuQScMedianade3 = new javax.swing.JMenuItem();
        MenuQuickSort = new javax.swing.JMenuItem();
        MenuSelectionSort = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arthur FMS - Laboratório de Estrutura de Dados - LEDA");
        setResizable(false);

        PainelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        GerarRelatorio.setText("Gerar Relatório");

        CancelarProcesso.setText("Cancelar Processo");
        CancelarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarProcessoActionPerformed(evt);
            }
        });

        BotaoIniciar.setText("Iniciar");
        BotaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(BotaoIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(CancelarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(GerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CancelarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(SaidaInformacoes);

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuPrincipal.setToolTipText("AAAAA");

        MenuGeralProjeto.setText("Projeto");

        Informacoes.setText("Informações");

        InfoGeral.setText("Gerais");
        InfoGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoGeralActionPerformed(evt);
            }
        });
        Informacoes.add(InfoGeral);

        ProjetoPasswords.setText("Projeto (Passwords)");
        Informacoes.add(ProjetoPasswords);

        SobreOAutor.setText("Sobre o Autor");
        SobreOAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreOAutorActionPerformed(evt);
            }
        });
        Informacoes.add(SobreOAutor);

        MenuGeralProjeto.add(Informacoes);
        MenuGeralProjeto.add(jSeparator1);

        Algoritmos.setText("Algorítmos");

        MenuCountingSort.setText("Counting Sort");
        MenuCountingSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCountingSortActionPerformed(evt);
            }
        });
        Algoritmos.add(MenuCountingSort);

        MenuHeapSort.setText("Heap Sort");
        Algoritmos.add(MenuHeapSort);

        MenuInsertionSort.setText("Insertion Sort");
        Algoritmos.add(MenuInsertionSort);

        MenuMergeSort.setText("Merge Sort");
        Algoritmos.add(MenuMergeSort);

        MenuQScMedianade3.setText("Q.S c/ Mediana de 3");
        Algoritmos.add(MenuQScMedianade3);

        MenuQuickSort.setText("Quick Sort");
        Algoritmos.add(MenuQuickSort);

        MenuSelectionSort.setText("Selection Sort");
        Algoritmos.add(MenuSelectionSort);

        MenuGeralProjeto.add(Algoritmos);

        MenuPrincipal.add(MenuGeralProjeto);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoGeralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoGeralActionPerformed

    private void MenuCountingSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCountingSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCountingSortActionPerformed

    private void CancelarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarProcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarProcessoActionPerformed

    private void BotaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoIniciarActionPerformed
        
    }//GEN-LAST:event_BotaoIniciarActionPerformed

    private void SobreOAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreOAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SobreOAutorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Algoritmos;
    private javax.swing.JButton BotaoIniciar;
    private javax.swing.JButton CancelarProcesso;
    private javax.swing.JButton GerarRelatorio;
    private javax.swing.JMenuItem InfoGeral;
    private javax.swing.JMenu Informacoes;
    private javax.swing.JMenuItem MenuCountingSort;
    private javax.swing.JMenu MenuGeralProjeto;
    private javax.swing.JMenuItem MenuHeapSort;
    private javax.swing.JMenuItem MenuInsertionSort;
    private javax.swing.JMenuItem MenuMergeSort;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenuItem MenuQScMedianade3;
    private javax.swing.JMenuItem MenuQuickSort;
    private javax.swing.JMenuItem MenuSelectionSort;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JMenuItem ProjetoPasswords;
    private javax.swing.JTextPane SaidaInformacoes;
    private javax.swing.JMenuItem SobreOAutor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
